language: python

python:
  - "2.7"
  # - "3.5"

install:
  - sudo apt-get install libnss3-tools

script:
    - certutil -L /etc/pki/pki
    - python -m unittest discover tests -p '*.py'

notifications:
    email:
      recipients:
          - fbarreto@redhat.com
      on_success: change
      on_failure: always

