language: python

python:
  - 2.7
  - 3.5

script:
	- python -m unittest discover tests -p '*.py'

notifications:
    email:
        recipients:
            - fbarreto@redhat.com

        on_success: change
        on_failure: always
