language: python

python:
  - "2.7"

env:
  - IS_TRAVIS=True

before_install:
  - pip install pyyaml
  - sudo apt-get install -y libnss3-tools

script:
    - python -m unittest discover tests -p '*.py'

notifications:
    email:
      recipients:
          - fbarreto@redhat.com
      on_success: change
      on_failure: always

