language: python

python:
  - "2.7"
  - "3.5"

install:
  - sudo apt-get install -y libnss3-tools
  - sudo apt-get install -y software-properties-common python-software-propertie
  - sudo add-apt-repository -y ppa:freeipa/ppa
  - sudo apt-get install -y freeipa-server

script:
    - python -m unittest discover tests -p '*.py'

notifications:
    email:
      recipients:
          - fbarreto@redhat.com
      on_success: change
      on_failure: always

