
# used in the full_check command
certs:
  - path: '/etc/pki/pki-tomcat/alias'
    name: 'caSigningCert cert-pki-ca'
    trustflags: 'CTu,Cu,Cu'
    monitored: false
    type: 'nssdb'

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'Server-Cert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: false
    type: 'nssdb'

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'auditSigningCert cert-pki-ca'
    trustflags: 'u,u,Pu'
    monitored: true
    type: 'nssdb'

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'ocspSigningCert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: true
    type: 'nssdb'

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'subsystemCert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: false
    type: 'nssdb'

  - path: '/etc/pki/tls/cert.pem'
    type: 'pem'

  - path: '/etc/ipa/ca.crt'
    type: 'crt'

# used in the ck_kra_setup command
kra_setup:
  kra_dir: '/etc/pki/pki-tomcat/kra'
  cert_path: '/etc/pki/pki-tomcat/alias'

# used in the ck_ra_cert command
ck_ra_cert:
  pem_dir: '/var/lib/ipa/ra-agent.pem'
  nssdb_dir: '/etc/httpd/alias'
