
# used in the full_check command
certs:
  - path: '/etc/pki/pki-tomcat/alias'
    name: 'caSigningCert cert-pki-ca'
    trustflags: 'CTu,Cu,Cu'
    monitored: false

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'Server-Cert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: false

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'auditSigningCert cert-pki-ca'
    trustflags: 'u,u,Pu'
    monitored: true

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'ocspSigningCert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: true

  - path: '/etc/pki/pki-tomcat/alias'
    name: 'subsystemCert cert-pki-ca'
    trustflags: 'u,u,u'
    monitored: false

# used in the certs_expired command
certs_expired:
    - path: '/etc/pki/pki-tomcat/alias'

# used in the ck_kra_setup command
kra_setup:
    kra_dir: '/etc/pki/pki-tomcat/kra'
    cert_path: '/etc/pki/pki-tomcat/alias'
